/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EquiblesCryptos);
  }
}(this, function(expect, EquiblesCryptos) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('News', function() {
      beforeEach(function() {
        instance = new EquiblesCryptos.News();
      });

      it('should create an instance of News', function() {
        // TODO: update the code to test News
        expect(instance).to.be.a(EquiblesCryptos.News);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property ampUrl (base name: "ampUrl")', function() {
        // TODO: update the code to test the property ampUrl
        expect(instance).to.have.property('ampUrl');
        // expect(instance.ampUrl).to.be(expectedValueLiteral);
      });

      it('should have the property articleUrl (base name: "articleUrl")', function() {
        // TODO: update the code to test the property articleUrl
        expect(instance).to.have.property('articleUrl');
        // expect(instance.articleUrl).to.be(expectedValueLiteral);
      });

      it('should have the property author (base name: "author")', function() {
        // TODO: update the code to test the property author
        expect(instance).to.have.property('author');
        // expect(instance.author).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property imageUrl (base name: "imageUrl")', function() {
        // TODO: update the code to test the property imageUrl
        expect(instance).to.have.property('imageUrl');
        // expect(instance.imageUrl).to.be(expectedValueLiteral);
      });

      it('should have the property keywords (base name: "keywords")', function() {
        // TODO: update the code to test the property keywords
        expect(instance).to.have.property('keywords');
        // expect(instance.keywords).to.be(expectedValueLiteral);
      });

      it('should have the property financialAssets (base name: "financialAssets")', function() {
        // TODO: update the code to test the property financialAssets
        expect(instance).to.have.property('financialAssets');
        // expect(instance.financialAssets).to.be(expectedValueLiteral);
      });

      it('should have the property publishedTime (base name: "publishedTime")', function() {
        // TODO: update the code to test the property publishedTime
        expect(instance).to.have.property('publishedTime');
        // expect(instance.publishedTime).to.be(expectedValueLiteral);
      });

      it('should have the property publisherName (base name: "publisherName")', function() {
        // TODO: update the code to test the property publisherName
        expect(instance).to.have.property('publisherName');
        // expect(instance.publisherName).to.be(expectedValueLiteral);
      });

    });
  });

}));
