/*
 * Cryptos
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AssetType} from './model/AssetType';
import {CryptoCurrencyProfile} from './model/CryptoCurrencyProfile';
import {CryptoCurrencyProfileResponse} from './model/CryptoCurrencyProfileResponse';
import {CryptoCurrencyProfilesResponse} from './model/CryptoCurrencyProfilesResponse';
import {Exchange} from './model/Exchange';
import {Image} from './model/Image';
import {Price} from './model/Price';
import {PricesResponse} from './model/PricesResponse';
import {ResponseStatus} from './model/ResponseStatus';
import {CryptosApi} from './api/CryptosApi';
import {PricesApi} from './api/PricesApi';

/**
* h3Authenticationh3____________________You_need_to_authenticate_to_use_this_API_____________________To_authenticate_click_on_the_Authorize_button_and_do_one_of_the_following_steps_br_____________________1__Send_your_API_key_in_the_headers_of_the_request_by_typing_Bearer_my_key_on_the_Bearer_authorization_scheme_br_____________________2__Send_your_API_key_on_the_ApiKey_query_string_parameter__To_do_this_type_your_API_key_in_the_Query_String_authorization_scheme_br_____________________Both_methods_are_equally_valid__We_offer_both_options_so_that_you_can_use_the_method_that_is_easier_to_use_in_your_application_br_____________________br_____________________h3API_limitsh3____________________Your_API_key_may_be_subject_to_dailyhourly_limits__To_know_how_much_requests_you_have_left_look_at_the_following_headers_in_the_response_br_____________________1__strongx_ratelimit_limitstrong___The_total_number_of_requests_that_you_are_allowed_to_make_in_a_given_period__hourday______________________2__strongx_ratelimit_remainingstrong___The_number_of_remaining_requests_that_you_can_perform_in_the_current_period_br_____________________3__strongx_ratelimit_resetstrong___The_number_of_seconds_until_the_current_period_resets_br_____________________br_____________________h3Suggestionsh3____________________You_dont_need_to_implement_the_whole_API_by_hand_in_your_programming_language_of_choice_br_____________________Since_this_API_has_an_OpenAPI_specification_you_can_use_____________________a_hrefhttpsgithub_comswagger_apiswagger_codegen_target_blankSwagger_Generatora_____________________to_automatically_generate_client_stubs_for_more_than_30_programming_languages_____________________br_____________________br_____________________You_dont_have_an_API_key_a_hrefhttpswww_equibles_comapipricing_target_blankGet_one_for_free_here_a.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EquiblesCryptos = require('index'); // See note below*.
* var xxxSvc = new EquiblesCryptos.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EquiblesCryptos.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EquiblesCryptos.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EquiblesCryptos.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssetType model constructor.
     * @property {module:model/AssetType}
     */
    AssetType,

    /**
     * The CryptoCurrencyProfile model constructor.
     * @property {module:model/CryptoCurrencyProfile}
     */
    CryptoCurrencyProfile,

    /**
     * The CryptoCurrencyProfileResponse model constructor.
     * @property {module:model/CryptoCurrencyProfileResponse}
     */
    CryptoCurrencyProfileResponse,

    /**
     * The CryptoCurrencyProfilesResponse model constructor.
     * @property {module:model/CryptoCurrencyProfilesResponse}
     */
    CryptoCurrencyProfilesResponse,

    /**
     * The Exchange model constructor.
     * @property {module:model/Exchange}
     */
    Exchange,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PricesResponse model constructor.
     * @property {module:model/PricesResponse}
     */
    PricesResponse,

    /**
     * The ResponseStatus model constructor.
     * @property {module:model/ResponseStatus}
     */
    ResponseStatus,

    /**
    * The CryptosApi service constructor.
    * @property {module:api/CryptosApi}
    */
    CryptosApi,

    /**
    * The PricesApi service constructor.
    * @property {module:api/PricesApi}
    */
    PricesApi
};
